
import { Language } from "./types";

export const COMMON_INGREDIENTS_BY_LANG: Record<Language, string[]> = {
  'pt-BR': [
    "Frango", "Ovos", "Arroz", "Batata", "Tomate", "Cebola", "Alho", 
    "Queijo", "Leite", "Farinha", "Macarrão", "Carne Moída", "Limão", 
    "Cenoura", "Abobrinha", "Bacon", "Manteiga", "Azeite", "Chocolate", 
    "Banana", "Aveia", "Atum", "Milho", "Feijão", "Pão"
  ],
  'en': [
    "Chicken", "Eggs", "Rice", "Potato", "Tomato", "Onion", "Garlic", 
    "Cheese", "Milk", "Flour", "Pasta", "Ground Beef", "Lemon", 
    "Carrot", "Zucchini", "Bacon", "Butter", "Olive Oil", "Chocolate", 
    "Banana", "Oats", "Tuna", "Corn", "Beans", "Bread"
  ],
  'es': [
    "Pollo", "Huevos", "Arroz", "Patata", "Tomate", "Cebolla", "Ajo", 
    "Queso", "Leche", "Harina", "Pasta", "Carne Molida", "Limón", 
    "Zanahoria", "Calabacín", "Tocino", "Mantequilla", "Aceite", "Chocolate", 
    "Plátano", "Avena", "Atún", "Maíz", "Frijoles", "Pan"
  ]
};

export const RECIPE_TYPES = {
  NORMAL: "Clássica",
  ECONOMICA: "Econômica",
  FITNESS: "Fitness",
  RAPIDA: "Rápida",
  SEM_FOGAO: "Sem Fogão"
};

export const TRANSLATIONS = {
  'pt-BR': {
    subtitle: "AI Kitchen",
    inputTitle: "O que tem na geladeira?",
    inputSubtitle: "Adicione até 3 ingredientes principais",
    noIngredients: "Nenhum ingrediente selecionado",
    placeholderLimit: "Limite atingido",
    placeholderNormal: "Ex: Cenoura, Ovo...",
    generateBtn: "Gerar Receita Mágica",
    loadingBtn: "Cozinhando Ideias...",
    classic: "Clássica",
    fitness: "Fitness",
    economic: "Econômica",
    quick: "Rápida",
    noStove: "Sem Fogão",
    save: "Salvar no Histórico",
    export: "Salvar Imagem",
    share: "Partilhar",
    ingredientsTitle: "Ingredientes",
    prepTitle: "Modo de Preparo",
    chefTip: "Dica do Chef",
    footerText: "AI Kitchen",
    variationsTitle: "Experimente uma versão diferente",
    historyEmptyTitle: "Histórico Vazio",
    historyEmptySub: "Suas receitas geradas aparecerão aqui.",
    historyTitle: "Suas Receitas",
    clearHistory: "Limpar",
    confirmClear: "Tem certeza que deseja apagar todo o histórico?",
    easy: "Fácil",
    exportError: "A ferramenta de exportação ainda está carregando.",
    genError: "Não foi possível criar a receita. Tente novamente.",
    creatingVersion: "Criando nova versão...",
    generateImageBtn: "Gerar Foto do Prato",
    generatingImage: "Criando Imagem...",
    downloadImage: "Baixar Foto",
    copyText: "Copiar Receita",
    copySuccess: "Copiado!",
    imageGenError: "Erro ao gerar imagem.",
    adLabel: "Publicidade",
    invalidIngredientsError: "Por favor, insira apenas ingredientes comestíveis válidos.",
    oops: "Ops!",
    success: "Sucesso!",
    shareTitle: "Preparando Partilha...",
    shareTextCopied: "Texto copiado! Cole na legenda.",
    shareError: "Erro ao partilhar. A imagem foi salva.",
    newRecipeBtn: "Gerar Nova Receita"
  },
  'en': {
    subtitle: "AI Kitchen",
    inputTitle: "What's in the fridge?",
    inputSubtitle: "Add up to 3 main ingredients",
    noIngredients: "No ingredients selected",
    placeholderLimit: "Limit reached",
    placeholderNormal: "Ex: Carrot, Egg...",
    generateBtn: "Generate Magic Recipe",
    loadingBtn: "Cooking Ideas...",
    classic: "Classic",
    fitness: "Fitness",
    economic: "Budget",
    quick: "Quick",
    noStove: "No Stove",
    save: "Save to History",
    export: "Save Image",
    share: "Share",
    ingredientsTitle: "Ingredients",
    prepTitle: "Instructions",
    chefTip: "Chef's Tip",
    footerText: "AI Kitchen",
    variationsTitle: "Try a different version",
    historyEmptyTitle: "Empty History",
    historyEmptySub: "Your generated recipes will appear here.",
    historyTitle: "Your Recipes",
    clearHistory: "Clear",
    confirmClear: "Are you sure you want to clear history?",
    easy: "Easy",
    exportError: "Export tool is still loading.",
    genError: "Could not create recipe. Please try again.",
    creatingVersion: "Creating new version...",
    generateImageBtn: "Generate Dish Photo",
    generatingImage: "Creating Image...",
    downloadImage: "Download Photo",
    copyText: "Copy Recipe",
    copySuccess: "Copied!",
    imageGenError: "Error generating image.",
    adLabel: "Advertisement",
    invalidIngredientsError: "Please enter only valid edible ingredients.",
    oops: "Oops!",
    success: "Success!",
    shareTitle: "Preparing Share...",
    shareTextCopied: "Text copied! Paste it in your caption.",
    shareError: "Share failed. Image saved instead.",
    newRecipeBtn: "Generate New Recipe"
  },
  'es': {
    subtitle: "Cocina IA",
    inputTitle: "¿Qué hay en la nevera?",
    inputSubtitle: "Añade hasta 3 ingredientes principales",
    noIngredients: "Ningún ingrediente seleccionado",
    placeholderLimit: "Límite alcanzado",
    placeholderNormal: "Ej: Zanahoria, Huevo...",
    generateBtn: "Generar Receta Mágica",
    loadingBtn: "Cocinando Ideas...",
    classic: "Clásica",
    fitness: "Fitness",
    economic: "Económica",
    quick: "Rápida",
    noStove: "Sin Estufa",
    save: "Guardar en Historial",
    export: "Guardar Imagen",
    share: "Compartir",
    ingredientsTitle: "Ingredientes",
    prepTitle: "Instrucciones",
    chefTip: "Consejo del Chef",
    footerText: "Cocina IA",
    variationsTitle: "Prueba una versión diferente",
    historyEmptyTitle: "Historial Vacío",
    historyEmptySub: "Tus recetas generadas aparecerán aquí.",
    historyTitle: "Tus Recetas",
    clearHistory: "Limpiar",
    confirmClear: "¿Estás seguro de borrar el historial?",
    easy: "Fácil",
    exportError: "La herramienta de exportación está cargando.",
    genError: "No se pudo crear la receta. Inténtalo de nuevo.",
    creatingVersion: "Creando nueva versión...",
    generateImageBtn: "Generar Foto del Plato",
    generatingImage: "Creando Imagen...",
    downloadImage: "Descargar Foto",
    copyText: "Copiar Receta",
    copySuccess: "¡Copiado!",
    imageGenError: "Error al generar imagen.",
    adLabel: "Publicidad",
    invalidIngredientsError: "Por favor, introduzca solo ingredientes comestibles válidos.",
    oops: "¡Ups!",
    success: "¡Éxito!",
    shareTitle: "Preparando...",
    shareTextCopied: "¡Texto copiado! Pégalo en la descripción.",
    shareError: "Error al compartir. Imagen guardada.",
    newRecipeBtn: "Generar Nueva Receta"
  }
};
